name: Spring Boot CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: ''

      - name: Check Gradle wrapper permissions
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon


      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST https://api.render.com/deploy/YOUR_RENDER_PROJECT_ID \
          -H "Authorization: Bearer $RENDER_API_KEY"